apiVersion: v1
kind: Namespace
metadata:
  name: chaos-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-stress
  namespace: chaos-app
  labels:
    app: io-stress
  annotations:
    # Annotation for Litmus
    litmuschaos.io/chaos: "true"
spec:
  selector:
    matchLabels:
      app: io-stress
  template:
    metadata:
      labels:
        app: io-stress
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: io-stress
          image: iskorotkov/chaos-io-stress:v0.1.0
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 8811
